baseURL = "https://lifrank0406.github.io/"
languageCode = "en-us"
title = "Frank Li"
theme = "PaperMod"
enableRobotsTXT = true
[params]
	showReadingTime = true
    homeInfoParams.Title = 'Hi there!'
    homeInfoParams.Content = "Notes, projects, blog."
	[[params.socialIcons]]
		name = "github"
		url  = "https://github.com/lifrank0406"
	[[params.socialIcons]]
		name = "LinkedIn"
		url  = "https://www.linkedin.com/in/frank-li-0b82b71a1/"