baseURL = "https://lifrank0406.github.io/"
languageCode = "en-us"
title = "Frank Li"
theme = "PaperMod"
enableRobotsTXT = true
[markup.goldmark.renderer]
unsafe = true
[params]
showReadingTime = true
disableAnchoredHeadings = true
math = true
[params.homeInfoParams]
Title = 'Hi there!'
Content = "Here are some things I've worked on and thought about!"
[[params.socialIcons]]
name = "github"
url  = "https://github.com/lifrank0406"
[[params.socialIcons]]
name = "LinkedIn"
url  = "https://www.linkedin.com/in/frank-li-0b82b71a1/"