baseURL = "https://lifrank0406.github.io/"
languageCode = "en-us"
title = "Frank Li"
theme = "PaperMod"
enableRobotsTXT = true
[params]
	showReadingTime = true
    # homeInfoParams.Title = 'Hi there!'
    # homeInfoParams.Content = "Notes, projects, blog."
	# [[params.socialIcons]]
		# name = "github"
		# url  = "https://github.com/lifrank0406"
	# [[params.socialIcons]]
		# name = "LinkedIn"
		# url  = "https://www.linkedin.com/in/frank-li-0b82b71a1/"
	[params.profileMode]
		enabled = true
		title   = "Frank Li"
		subtitle= "Notes • Projects"
		imageUrl = "/dog.jfif"
		imageTitle = "Frank"
		imageWidth = 160
		imageHeight = 160

		[[params.profileMode.buttons]]
			name = "Posts"
			url  = "/posts/"
	
		[[params.socialIcons]]
			name = "github"
			url  = "https://github.com/lifrank0406"
		[[params.socialIcons]]
			name = "LinkedIn"
			url  = "https://www.linkedin.com/in/frank-li-0b82b71a1/"